### ISSUE TITLE
Kali Linux boot animation not working

### ISSUE THREAD

**Issue by disc0nct** [VandalByte/dedsec-grub2-theme#21]
After installing the theme and follow the tweak instructions, the Kali Plymouth/splash screen does not work even trying these commands.
`sudo plymouth-set-default-theme kali -R && sudo update-grub`

**Comment by VandalByte** [comment]
Hi @disc0nct 
I'm sorry but I don't have much experience with plymouth customization so I would suggest you ask the dev who made that theme (if it's a custom theme) or consider asking in the Kali forums if it's the default theme. I'm sure it's not because of the grub theme installation because I test all my themes in Kali Linux and I have never experienced such issue.
